### ISSUE TITLE
Joining forces with twirp-ts

### ISSUE THREAD

**Issue by fenos** [tatethurston/TwirpScript#1]
Hello, nice to meet you!
I'm the author of [twirp-ts](https://github.com/hopin-team/twirp-ts)

I'm glad to see other server implementations in Typescript for twirp!

However, I was wondering what's the reason that pushed you to create a new twirp implementation over contributing to `twirp-ts` ?

We are using twirp-ts heavily internally and I'm willing to improve it as much as necessary, maybe we can join forces as I think that twirp-ts is a bit more mature?

If not, that's ok. 
Different implementations would also bring new innovations. 

Take care and good job!

**Comment by tatethurston** [comment]
Hello!

I actually started this project awhile back, before `twirp-ts` was available. When I have some time I'll play around with `twirp-ts`.

Thus far, I've focused on the following for TwirpScript:

- Lean on Google's protobuf library as much as possible
- Generate idiomatic JS interfaces (eg none of the Java idioms that Google's JS implementation presents like  `$fieldList` for array types).
- A client optimized for consumption in the browser
- Preserving comments as inline documentation

With this project I'm specifically interested in exploring the DX surrounding traditional full stack web applications where there is 1 server and 1 client. For multiple clients, I would pull in GraphQL, but for a single client I prefer the simpler architecture (and well defined optimization paths) found with a more traditional API server approach. A JSON API lacks the type safety I'm looking for. JSON Schema is another approach to solving this problem, but I was interested in exploring Twirp's approach to this problem.

**Comment by fenos** [comment]
Hello @tatethurston sorry for the late reply!

I see! that make sense, 

> Lean on Google's protobuf library as much as possible Generate idiomatic JS interfaces (eg none of the Java idioms that Google's JS implementation presents like $fieldList for array types).

twirp-ts is based off ts-proto or the awesome @protobuf-ts for message code generation not really compatible with the standard google's JS implementation.

> A client optimized for consumption in the browser

In regards of the browser compatibility I'm looking for a clean way to implement that, your approach might be very beneficial to the library

> Preserving comments as inline documentation

This is something that I'll add as well!

Again, well done with the implementation, if you ever pass by on twirp-ts feel free to leave some feedback
