### ISSUE TITLE
Service Name Generation

### ISSUE THREAD

**Issue by arranf** [tatethurston/TwirpScript#104]
[Buf](https://github.com/bufbuild/buf)'s default lint settings requires services to end in service i.e. `HaberdasherService` rather than `Haberdasher`.

If you follow that convention, TwirpScript generates `HaberdasherServiceService`

**Comment by tatethurston** [comment]
Cool, that makes sense to me. I think this service suffix is coming from `google-protobuf`, I think the only name manipulation I do is camelCasing.

Speaking of which, because this will be a breaking change, what do you think about camel casing the service and method names while we're in here?
