### ISSUE TITLE
Reducing Scope of Generated Files

### ISSUE THREAD

**Issue by arranf** [tatethurston/TwirpScript#113]
We are using a model where we have a git submodule in our services which contains the `.proto` definitions for our services.

Running `yarn twirpscript` generates unneeded `.pb.ts` definitions as a result. It'd be nice to be able to scope which `.proto` files are used for generation.

I'd propose using the same model as npm where you can either include a `files` array of `.proto` files in the `.twirp.json` to include or include a `.twirpignore` file which would allow you to specify globs of paths to ignore.

I'd be happy to do the leg work on this.

**Comment by tatethurston** [comment]
Yeah this addition totally makes sense to me. What do you think about something like include / [exclude](https://www.typescriptlang.org/tsconfig#exclude) from tsconfig?

I think I'd like to keep all the twirp parameters in `.twirp.json` instead of having multiple files. I've been thinking about also accepting twirp parameters from a key in `package.json` -- I can't remember if tools and the broader JS ecosystem are leaning into or away from that approach.

LMK your thoughts.

**Comment by tatethurston** [comment]
As a follow up question, if TwirpScript integrated with `buf` as a [plugin](https://docs.buf.build/tour/generate-code) would you prefer to use `buf` instead of running `yarn twirpscript`?

**Comment by arranf** [comment]
> As a follow up question, if TwirpScript integrated with `buf` as a [plugin](https://docs.buf.build/tour/generate-code) would you prefer to use `buf` instead of running `yarn twirpscript`?

I don't think so! I think I'd be open to the idea but I don't think that'd be more helpful with our current workflow (although I'm certain that'll evolve over time!) 

What do you see the advantage as here?

> Yeah this addition totally makes sense to me. What do you think about something like include / [exclude](https://www.typescriptlang.org/tsconfig#exclude) from tsconfig?
> 
> I think I'd like to keep all the twirp parameters in `.twirp.json` instead of having multiple files. I've been thinking about also accepting twirp parameters from a key in `package.json` -- I can't remember if tools and the broader JS ecosystem are leaning into or away from that approach.
> 
> LMK your thoughts.

Yep that totally makes sense to me! I'm of the opinion that the `package.json` gets overly stuffed full of config so where possible I've avoided using that. A specific it makes specific tooling's config easier to parse and modify IMO too! I'd be happy to support `includes` and `excludes` in `.twirp.json` - it makes a lot of sense to me.

**Comment by tatethurston** [comment]
> I don't think so! I think I'd be open to the idea but I don't think that'd be more helpful with our current workflow (although I'm certain that'll evolve over time!)

> What do you see the advantage as here?

The benefits would be piggy backing on work `buf` has already done (such as path `excludes`. Also condensing any code pipelines like `buf && yarn twripscript` to simply `buf`.

> Yep that totally makes sense to me! I'm of the opinion that the package.json gets overly stuffed full of config so where possible I've avoided using that. A specific it makes specific tooling's config easier to parse and modify IMO too! 

That makes sense to me.

> I'd be happy to support includes and excludes in .twirp.json - it makes a lot of sense to me.

Great, do you want to take a swing at the implementation? I'm happy to help where needed.

**Comment by arranf** [comment]
@tatethurston Definitely. I'm hoping I'll be able to dedicate some time to it (and cleaning up my other PR!) this week.

**Comment by tatethurston** [comment]
fixed in #127
