### ISSUE TITLE
Type check error with map field type

### ISSUE THREAD

**Issue by antonioorct** [tatethurston/TwirpScript#120]
.proto
`map<string, int32> beaconCountByStatus = 1;`

![image](https://user-images.githubusercontent.com/14859262/152956475-a99669a1-e435-40b6-a2b1-a027d7db04e7.png)
![image](https://user-images.githubusercontent.com/14859262/152956494-9b60a798-0ff1-4ab5-bde5-7639e08fb806.png)

Manually adding the .entries type arguments fixes it:
![image](https://user-images.githubusercontent.com/14859262/152956548-3071fba0-aff6-4c3a-a995-ca43624451a8.png)

**Comment by tatethurston** [comment]
Thanks @antonioorct this is fixed in [v.0.0.45](https://github.com/tatethurston/TwirpScript/releases/tag/v0.0.45)
