### ISSUE TITLE
TwirpScript  0.0.44 fails to compile with noUnusedLocals TSConfig Option with Empty Parameters

### ISSUE THREAD

**Issue by arranf** [tatethurston/TwirpScript#121]
TwirpScript  0.0.44 fails to compile with noUnusedLocals TSConfig Option due to the `_readMessageJSON`'s `json` parameter.

**Comment by tatethurston** [comment]
Thanks @arranf this is fixed in https://github.com/tatethurston/TwirpScript/releases/tag/v0.0.45
