### ISSUE TITLE
Possible Regression in 0.0.44 and 0.0.45. Empty repeated fields aren't serialized in JSON Responses

### ISSUE THREAD

**Issue by arranf** [tatethurston/TwirpScript#123]
`repeated` fields stopped being serialised in JSON responses if the runtime array is empty in 0.0.44. Prior to this they were always included.

I understand for protobufs all fields are optional by default - I'm not sure what the correct behaviour is for JSON.

Example
```
message Example {
  int32 id = 1;
  repeated Sample samples = 2; /
}

message Sample {
  int32 id = 1;
}
```

**Comment by tatethurston** [comment]
Hey @arranf this spec should be treated as the source of truth for protobuf JSON: https://developers.google.com/protocol-buffers/docs/proto3#json

TwirpScript isn't _quite_ in spec yet, but this is the expected behavior. Do you need a different behavior?

**Comment by arranf** [comment]
> Hey @arranf this spec should be treated as the source of truth for protobuf JSON: https://developers.google.com/protocol-buffers/docs/proto3#json
> 
> TwirpScript isn't _quite_ in spec yet, but this is the expected behavior. Do you need a different behavior?

Thanks for that link! Ideally - yes, we would have the option to serialize them differently but I'm very aware that as that's out of spec that's probably not in the best interests of the library.

**Comment by arranf** [comment]
> The spec calls out providing an option for different serialization semantics (similar to changing the json name). How would you like them to be serialized?

I think not including them is a sensible default behaviour but if possible it'd be great to have an option to (per project) have them serialize as an empty array instead!

**Comment by tatethurston** [comment]
Hey @arranf setting the new json.emitFieldsWithDefaultValues option to true should cover this case. LMK if you run into any issues
