### ISSUE TITLE
Enum methods with suffix ToInt not importeds

### ISSUE THREAD

**Issue by alexisvisco** [tatethurston/TwirpScript#150]
Hi, 

While  generating a proto with a enum in another package, methods with ToInt arn't imported. 

Example https://github.com/alexisvisco/protocol-example/tree/enum-does-not-works

**Comment by tatethurston** [comment]
Hey @alexisvisco thanks for reporting. Could you give me a little more context here? Which file(s) should I be looking at?

**Comment by alexisvisco** [comment]
https://github.com/alexisvisco/protocol-example/blob/enum-does-not-works/protos/leads/v1/leads.proto#L85 

When you are generating the code you will see an error in your editor, or when building typescript files

**Comment by tatethurston** [comment]
Ah, got it. Thanks @alexisvisco, I see what's going on here. This is a regression I introduced when I migrated to a string representation for enums.
