### ISSUE TITLE
Map seems does not works properly

### ISSUE THREAD

**Issue by alexisvisco** [tatethurston/TwirpScript#151]
Hi,

When adding a map with a type it seems like the generated code not compile. 

Example repository : https://github.com/alexisvisco/protocol-example/tree/maps-does-not-works

With this property https://github.com/alexisvisco/protocol-example/blob/maps-does-not-works/protos/leads/v1/leads.proto#L70

**Comment by alexisvisco** [comment]
```
Argument type (msg: MapMessage<CreateRequest.LenderPlans>) => Record<string, unknown> is not assignable to parameter type (value: {value: any, key: string}, index: number, array: {value: any, key: string}[]) => Record<string, unknown>

Argument type (number | LenderLoanPlan | undefined)[][] is not assignable to parameter type Iterable<readonly [PropertyKey, (number | undefined)]>

Argument type (msg: MapMessage<ComputeDatedLoanPlansResponse.LenderPlans>, json: any) => MapMessage<ComputeDatedLoanPlansResponse.LenderPlans> is not assignable to parameter type (value: {value: any, key: string}, index: number, array: {value: any, key: string}[]) => MapMessage<ComputeDatedLoanPlansResponse.LenderPlans>
```

**Comment by tatethurston** [comment]
@alexisvisco could you confirm which version of TwirpScript and TypeScript you're using?

I see `"twirpscript": "^0.0.47"` in your example and no `yarn.lock`. Do you still run into this issue on `v0.0.50`?
