### ISSUE TITLE
Null message in response are filled with empty values

### ISSUE THREAD

**Issue by alexisvisco** [tatethurston/TwirpScript#162]
Hi ! 

When I receive a protobuf message with a field that is a message and is null, the decode will read the message and set default value for it. However it is null. 

Could you please fix this bug ? :)

**Comment by tatethurston** [comment]
Hey @alexisvisco, a few questions:

1. Is this during a JSON or Protobuf decoding?
2. Is this an optional field?

**Comment by alexisvisco** [comment]
1. It is with the protobuf decoding
2. It is not an optional field but it is a message (not a native type)

I don't think message are serialized with default value because in Go message field are generated with pointers and when you provide nothing for a field that is a message it put a null pointer. 

Is this more clear to you ?

**Comment by alexisvisco** [comment]
```
message FindByIdResponse {
  Dashboard dashboard = 1;
}
```

If I sent {} through the rpc method I will get a nil dashboard and this is the correct behavior.

**Comment by tatethurston** [comment]
What's the reason to avoid marking dashboard as `optional`? https://developers.google.com/protocol-buffers/docs/proto#optional

```
message FindByIdResponse {
  optional Dashboard dashboard = 1;
}
```

This is more flexible because it enables consumers to decide the nullability semantics of a given field.

**Comment by alexisvisco** [comment]
https://stackoverflow.com/a/42634681/8810797 

In protobuf 3 all fields are optionals :)

**Comment by tatethurston** [comment]
That is not a correct interpretation of `optional` in protobuf -- we're overloading the term here.

> In proto3, all fields are "optional" (in that it is not an error if the sender fails to set them).

The author of the post is correct that it's not an error if the sender fails to send them -- in fact we generally don't send fields that are the default value under protobuf regardless of what the sender sets. That is an optimization we apply at the serialization layer to decrease the size of the message over the wire.

`optional` is used to determine the semantics on the deserialization side. Specifically, do we leave the value as a a bottom type (undefined / null / nil, etc) or do we "hydrate" with the default value.

**Comment by alexisvisco** [comment]
This is maybe a misunderstanding because optional was recently added in proto 3. 

However setting optional prefix to a field which is a message does not solve the problem. In my server implementation I return the field with a null value and the client get a message with default value, how am I supposed to know if the field is set or not ?

**Comment by tatethurston** [comment]
Optional message deserialization had a bug where the default message value was always being supplied. This has been fixed. Now if the server supplies an optional field with a null value the client will receive `undefined` for the field.
