### ISSUE TITLE
Sending requests through a proxy

### ISSUE THREAD

**Issue by jwlee-asp** [tatethurston/TwirpScript#186]
I have used http libraries with [hpagent](https://github.com/delvedor/hpagent) to send requests to a proxy. Is it possible to send requests made from the client through a proxy? I couldn't find a configuration with the client, but would there be an avenue using the middleware?

**Comment by tatethurston** [comment]
Hey @jwlee-asp thanks for opening this. I had thought that I had documented `rpcTransport` but it appears I haven't.

I believe [something like this](https://github.com/tatethurston/TwirpScript/issues/185#issuecomment-1197495356) would work, replacing `fetch` with your instance of `hpagent`. LMK if that works, or if you run into any issues.
