### ISSUE TITLE
root in config

### ISSUE THREAD

**Issue by Blancduman** [tatethurston/TwirpScript#199]
Hello.

Specifing a path with nesting in `root` -> `twirp.json` cause error.

```Error: Cannot find module 'path\to\protos\node_modules\twirpscript\dist\compiler.js'```

It's trying to find `compiler.js` in nested path, not in project's `nodes_modules` .

**Comment by Blancduman** [comment]
```json
{
   "root": "my/protos",
   "dest": "my/api"
}
```

**Comment by Blancduman** [comment]
And it's windows case

**Comment by tatethurston** [comment]
Thanks for reporting @Blancduman I’ll take a look

**Comment by tatethurston** [comment]
@Blancduman Can you let me know if you still encounter this issue on v0.0.63 https://github.com/tatethurston/TwirpScript/releases/tag/v0.0.63
