### ISSUE TITLE
Support for Nextjs 13 Fetch API

### ISSUE THREAD

**Issue by frankwoodi** [tatethurston/TwirpScript#221]
In nextjs 13, static rendering, ISR and SSR is determined only by the arguments in fetch. Since we have no access to fetch API and it’s features this is impossible
```JS
import { GetHat } from ‘./generated.pb’

async function Component({id}) {
    const hat = await GetHat({ id }).config({
    next: {
         revalidate: 1000,
         tags: ['collection']
       },
    cache: “no-store”
    })

return (<p>{hat}</p>)
}

}

```

**Comment by tatethurston** [comment]
@frankwood did you checkout the rpcTransport option?
 https://github.com/tatethurston/TwirpScript#rpctransport
