### ISSUE TITLE
Inexplicable bug occurring during code generation

### ISSUE THREAD

**Issue by matt-tyler** [tatethurston/TwirpScript#34]
Hey tate,

First of all, great work on this library. It was real easy for me to get a typescript flavored twirp server running on AWS Lambda.

The following results in an error when running `npx twirpscript`
```
message GetUserResponse {
    string user_id = 1;

    message Address {
        string id = 1;
        AddressValue value = 2;
    }

    message AddressList {
        repeated Address address = 1;
        Address primary = 2;
    }
    AddressList addresses = 2;
}

message AddressValue {
    optional string address_line1 = 1;
    optional string address_line2 = 2;
    optional string country_code = 3;
    optional string postcode = 4;
    optional string state = 5;
    optional string suburb = 6;
}
```
However, moving the "Address" message out to the top scope resolves the error. It's not clear to me exactly why this would be the case, and I've not seen this occur in other grpc/proto related generators.

Output error trace below.

```
~/projects/aws-twirp-cdk  main ✗                                                                                                                  3d ⚑ ◒  
▶ npx twirpscript
/Users/matt.tyler/projects/aws-twirp-cdk/node_modules/prettier/index.js:12990
      throw error;
      ^

SyntaxError: ',' expected. (1061:1)
  1059 |       }
  1060 |
> 1061 | AddressList: {
       | ^
  1062 |         writeMessage: function(msg : GetUserResponse.AddressList, writer: BinaryWriter): void {
  1063 |                           if (msg.address.length > 0) {
  1064 |                 writer.writeRepeatedMessage(1, msg.address as any, GetUserResponse.Address.writeMessage);
    at r (/Users/matt.tyler/projects/aws-twirp-cdk/node_modules/prettier/parser-typescript.js:1:557)
    at yx (/Users/matt.tyler/projects/aws-twirp-cdk/node_modules/prettier/parser-typescript.js:13:3304376)
    at Object.parse (/Users/matt.tyler/projects/aws-twirp-cdk/node_modules/prettier/parser-typescript.js:13:3304817)
    at Object.parse$d [as parse] (/Users/matt.tyler/projects/aws-twirp-cdk/node_modules/prettier/index.js:12975:19)
    at coreFormat (/Users/matt.tyler/projects/aws-twirp-cdk/node_modules/prettier/index.js:14525:16)
    at formatWithCursor$1 (/Users/matt.tyler/projects/aws-twirp-cdk/node_modules/prettier/index.js:14765:14)
    at /Users/matt.tyler/projects/aws-twirp-cdk/node_modules/prettier/index.js:60959:12
    at format (/Users/matt.tyler/projects/aws-twirp-cdk/node_modules/prettier/index.js:60979:12)
    at writeFile (/Users/matt.tyler/projects/aws-twirp-cdk/node_modules/twirpscript/dist/compiler.js:19:43)
    at /Users/matt.tyler/projects/aws-twirp-cdk/node_modules/twirpscript/dist/compiler.js:28:5 {
  loc: { start: { line: 1061, column: 1 } },
  codeFrame: '  1059 |       }\n' +
    '  1060 |\n' +
    '> 1061 | AddressList: {\n' +
    '       | ^\n' +
    '  1062 |         writeMessage: function(msg : GetUserResponse.AddressList, writer: BinaryWriter): void {\n' +
    '  1063 |                           if (msg.address.length > 0) {\n' +
    '  1064 |                 writer.writeRepeatedMessage(1, msg.address as any, GetUserResponse.Address.writeMessage);'
}
--twirpscript_out: protoc-gen-twirpscript: Plugin failed with status code 1.
```

Hopefully you will be able to make some sense of this!

**Comment by tatethurston** [comment]
Hey @matt-tyler thanks for the kind words and for reporting this bug. I'm glad to hear you were able to get a twirp service running on AWS lambda quickly. I've fixed the issue you ran into and published the fix in https://github.com/tatethurston/TwirpScript/releases/tag/v0.0.29

**Comment by tatethurston** [comment]
@matt-tyler Do you have any code (or a repository) you could share showing your lambda usage? I've been planning to add support and/or documentation for that use case.

**Comment by matt-tyler** [comment]
Thanks for the extremely prompt fix!

wrt: lambda

Not at the moment but honestly, it's not particularly difficult. `aws-lambda-go` publishes a bunch of helpers that wrap the standard go HTTP server and convert requests/response to/from the API Gateway format, so I went looking for something that takes the same approach in nodejs, which exists in @vendia/serverless-express.

```
const myService = proto.createMyServiceHandler(new MyService());
const app = createTwirpServer([myService]);

export const handler = serverlessExpress({ app });
```

So only a pretty minor change of what you already with respect to starting a server up. From there, the only important detail is ensuring that you use catchall route (/{proxy}+) when path matching in API Gateway, or match the path correctly.

**Comment by tatethurston** [comment]
Thanks @matt-tyler!

**Comment by tatethurston** [comment]
TwirpScript now exports a `createTwirpServerless` primitive for clients that want to deploy serverless TwirpScript handlers. The wiring isn't quite as succinct as serverlessExpress though! 

https://github.com/tatethurston/TwirpScript/blob/main/examples/aws-lambda/src/index.ts
