### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'content-type') at getRequestContext 

### ISSUE THREAD

**Issue by arranf** [tatethurston/TwirpScript#50]
Calling the basic example from the README from a client using the `nodeHttpTransport` on node v16 with TwirpScript v0.0.32 and TypeScript v4.5.4 results in an undefined access issue identifying the content-type of the request on the server.

Logs:
```
$ /Users/user/Projects/twirpscript_demo/node_modules/.bin/ts-node src/server/index.ts
Server listening on port 8080
/Users/user/Projects/twirpscript_demo/node_modules/twirpscript/dist/runtime/server/index.js:190
        contentType: (_a = contentTypeName[req.headers["content-type"]]) !== null && _a !== void 0 ? _a : "Unknown",
                                                      ^
TypeError: Cannot read properties of undefined (reading 'content-type')
    at getRequestContext (/Users/user/Projects/twirpscript_demo/node_modules/twirpscript/dist/runtime/server/index.js:190:55)
    at app (/Users/user/Projects/twirpscript_demo/node_modules/twirpscript/dist/runtime/server/index.js:224:21)
    at Server.app (/Users/user/Projects/twirpscript_demo/node_modules/twirpscript/dist/runtime/server/index.js:159:32)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
error Command failed with exit code 1.
```

Note that there is _some_ guarding against this in `validateRequest` but this is called _after_ `getRequestContext` which access the content-type header first. The headers seem to be present on the request but cannot be accessed via `req.headers`.

**Comment by tatethurston** [comment]
Hey @arranf thanks for reporting this and digging in. I'm going to move to mutating `body` on the request instead of keeping the object spread so we don't get bit by other request properties that aren't own enumberable.

I'm curious why we see a difference here based on the client, browser fetch vs node's http.
